In [1]:
#1. Create a NumPy Array
#@Task: Create a 1-dimensional NumPy array containing the numbers from 1 to 10.
import numpy as np

array_1d = np.arange(1, 11)
print(array_1d)


[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
#2. Array Operations
#Task: Create two 1-dimensional arrays of length 5 with random integers between 1 and 10. 
#Perform element-wise addition, subtraction, multiplication, and division on these arrays.
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


Array 1: [3 3 6 9 2]
Array 2: [10  7  1  3  9]
Addition: [13 10  7 12 11]
Subtraction: [-7 -4  5  6 -7]
Multiplication: [30 21  6 27 18]
Division: [0.3        0.42857143 6.         3.         0.22222222]


In [3]:
#3. Array Slicing
#Task: Create a 1-dimensional array of 20 elements with values ranging from 0 to 19. 
#Slice the array to get the first 10 elements, the last 10 elements, and every other element.
array = np.arange(20)

first_10 = array[:10]
last_10 = array[-10:]
every_other = array[::2]

print("Original array:", array)
print("First 10 elements:", first_10)
print("Last 10 elements:", last_10)
print("Every other element:", every_other)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
First 10 elements: [0 1 2 3 4 5 6 7 8 9]
Last 10 elements: [10 11 12 13 14 15 16 17 18 19]
Every other element: [ 0  2  4  6  8 10 12 14 16 18]


In [4]:
#4. Matrix Creation
#Task: Create a 3x3 matrix with values ranging from 1 to 9.
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#5. Matrix Operations
#Task: Create two 3x3 matrices with random integers between 1 and 10. 
#Perform matrix addition, subtraction, element-wise multiplication, and matrix multiplication.
matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

addition = matrix1 + matrix2
subtraction = matrix1 - matrix2
elementwise_multiplication = matrix1 * matrix2
matrix_multiplication = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", elementwise_multiplication)
print("Matrix Multiplication:\n", matrix_multiplication)


Matrix 1:
 [[ 4  8  6]
 [ 3  6  7]
 [ 3  1 10]]
Matrix 2:
 [[ 7  1  4]
 [ 7  4  9]
 [10  2  1]]
Addition:
 [[11  9 10]
 [10 10 16]
 [13  3 11]]
Subtraction:
 [[-3  7  2]
 [-4  2 -2]
 [-7 -1  9]]
Element-wise Multiplication:
 [[28  8 24]
 [21 24 63]
 [30  2 10]]
Matrix Multiplication:
 [[144  48  94]
 [133  41  73]
 [128  27  31]]


In [6]:
#6. Statistical Operations
#Task: Create a 1-dimensional array with 15 random integers between 1 and 100. 
#Calculate the mean, median, standard deviation, and variance of the array.
array = np.random.randint(1, 101, size=15)

mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Array:", array)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)


Array: [79 26 15  6 40 73 67 58 73 39 49 20 19 34 34]
Mean: 42.13333333333333
Median: 39.0
Standard Deviation: 22.591640538531554
Variance: 510.3822222222222


In [7]:
#7. Reshaping Arrays
#Task: Create a 1-dimensional array of 12 elements and reshape it into a 3x4 matrix.
array = np.arange(12).reshape(3, 4)
print(array)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
#8. Boolean Indexing
#Task: Create a 1-dimensional array of 10 random integers between 0 and 20. 
#Use boolean indexing to select elements greater than 10.
array = np.random.randint(0, 21, size=10)
greater_than_10 = array[array > 10]

print("Array:", array)
print("Elements greater than 10:", greater_than_10)


Array: [18  9  4  5 13 20 19  2  5 20]
Elements greater than 10: [18 13 20 19 20]


In [9]:
#1. Creating DataFrames
#Task: Create a DataFrame with three columns: 'Name', 'Age', and 'City', and five rows of data.
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

df = pd.DataFrame(data)
print(df)


      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eva   29      Phoenix


In [10]:
#2. Reading and Writing Data
#Task: Read a CSV file into a DataFrame and write the DataFrame to a new CSV file.

# Reading a CSV file
df = pd.read_csv('input.csv')
print(df)

# Writing to a new CSV file
df.to_csv('output.csv', index=False)


FileNotFoundError: [Errno 2] No such file or directory: 'input.csv'

In [11]:
#3. Basic DataFrame Operations
#Task: Create a DataFrame and demonstrate basic operations like selecting specific columns, 
#rows, and filtering based on conditions.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

df = pd.DataFrame(data)

# Select specific columns
print(df[['Name', 'City']])

# Select specific rows
print(df.iloc[1:3])

# Filtering based on conditions
print(df[df['Age'] > 25])


      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eva      Phoenix
      Name  Age         City
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
    Name  Age         City
1    Bob   27  Los Angeles
3  David   32      Houston
4    Eva   29      Phoenix


In [12]:
#4. DataFrame Statistics
#Task: Create a DataFrame with numerical data and calculate summary 
#statistics like mean, median, min, max, and standard deviation for each column.
data = {
    'A': [10, 20, 30, 40, 50],
    'B': [5, 15, 25, 35, 45],
    'C': [2, 4, 6, 8, 10]
}

df = pd.DataFrame(data)

print("Mean:\n", df.mean())
print("Median:\n", df.median())
print("Min:\n", df.min())
print("Max:\n", df.max())
print("Standard Deviation:\n", df.std())


Mean:
 A    30.0
B    25.0
C     6.0
dtype: float64
Median:
 A    30.0
B    25.0
C     6.0
dtype: float64
Min:
 A    10
B     5
C     2
dtype: int64
Max:
 A    50
B    45
C    10
dtype: int64
Standard Deviation:
 A    15.811388
B    15.811388
C     3.162278
dtype: float64


In [13]:
#5. Handling Missing Data
#Task: Create a DataFrame with some missing values and demonstrate how to fill, drop, or interpolate these missing values.
data = {
    'A': [1, 2, None, 4, 5],
    'B': [None, 2, 3, None, 5],
    'C': [1, None, 3, 4, None]
}

df = pd.DataFrame(data)

# Fill missing values
print("Fill NaN:\n", df.fillna(0))

# Drop rows with missing values
print("Drop NaN:\n", df.dropna())

# Interpolate missing values
print("Interpolate NaN:\n", df.interpolate())


Fill NaN:
      A    B    C
0  1.0  0.0  1.0
1  2.0  2.0  0.0
2  0.0  3.0  3.0
3  4.0  0.0  4.0
4  5.0  5.0  0.0
Drop NaN:
 Empty DataFrame
Columns: [A, B, C]
Index: []
Interpolate NaN:
      A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  2.0
2  3.0  3.0  3.0
3  4.0  4.0  4.0
4  5.0  5.0  4.0


In [14]:
#6. Grouping Data
#Task: Create a DataFrame and group the data based on one of the columns, then calculate the sum and mean for each group.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

df = pd.DataFrame(data)

# Group by 'City' and calculate sum and mean of 'Age'
grouped = df.groupby('City')['Age'].agg(['sum', 'mean'])
print(grouped)


             sum  mean
City                  
Chicago       22  22.0
Houston       32  32.0
Los Angeles   27  27.0
New York      24  24.0
Phoenix       29  29.0


In [15]:
#7. Merging DataFrames
#Task: Create two DataFrames with a common column and demonstrate how to 
#merge them using different types of joins (inner, outer, left, right).
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 4],
    'Age': [24, 27, 22]
})

# Inner join
print("Inner join:\n", pd.merge(df1, df2, on='ID', how='inner'))

# Outer join
print("Outer join:\n", pd.merge(df1, df2, on='ID', how='outer'))

# Left join
print("Left join:\n", pd.merge(df1, df2, on='ID', how='left'))

# Right join
print("Right join:\n", pd.merge(df1, df2, on='ID', how='right'))


Inner join:
    ID   Name  Age
0   1  Alice   24
1   2    Bob   27
Outer join:
    ID     Name   Age
0   1    Alice  24.0
1   2      Bob  27.0
2   3  Charlie   NaN
3   4      NaN  22.0
Left join:
    ID     Name   Age
0   1    Alice  24.0
1   2      Bob  27.0
2   3  Charlie   NaN
Right join:
    ID   Name  Age
0   1  Alice   24
1   2    Bob   27
2   4    NaN   22


In [16]:
#8. Pivot Tables
#Task: Create a DataFrame and generate a pivot table summarizing the data in a meaningful way.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Score': [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)

# Create a pivot table with average 'Score' for each 'City'
pivot_table = pd.pivot_table(df, values='Score', index='City', aggfunc='mean')
print(pivot_table)


             Score
City              
Chicago       78.0
Houston       92.0
Los Angeles   90.0
New York      85.0
Phoenix       88.0
